/** Vietnamese question stems for PRM393 (part 2: 110–171, Dart / Flutter ôn tập). */
export const qviB = {
  110: 'Lập trình bất đồng bộ trong Dart dùng để làm gì?',
  111: 'Lớp nào biểu diễn giá trị sẽ có trong tương lai?',
  112: 'Làm sao đánh dấu một hàm là bất đồng bộ trong Dart?',
  113: 'Từ khóa nào trong hàm async dùng để chờ một Future hoàn thành?',
  114: 'Kiểu trả về của hàm async trả về số nguyên là gì?',
  115: 'Đoạn mã này sẽ in ra gì?',
  116: 'Câu nào xử lý Future đúng bằng `.then()`?',
  117: 'Từ khóa nào có thể dùng cùng try/catch trong hàm async để xử lý lỗi?',
  118: 'Hàm này trả về gì?',
  119: 'Từ khóa nào dùng để khai báo biến trong Dart?',
  120: 'Cú pháp đúng để khai báo biến kiểu int trong Dart?',
  121: 'Phần nào sau đây không phải kiểu primitive trong Dart?',
  122: 'Giá trị mặc định của biến chưa khởi tạo trong Dart là gì?',
  123: 'Khai báo boolean hợp lệ nào sau đây?',
  124: 'Từ khóa nào dùng để khai báo biến không đổi giá trị?',
  125: 'Từ khóa `final` trong Dart có nghĩa là gì?',
  126: 'Khác biệt giữa `final` và `const` là gì?',
  127: 'Ký hiệu `?` sau tên kiểu trong Dart có nghĩa là gì?',
  128: 'Toán tử `??` làm gì?',
  129: 'Toán tử nào gán giá trị chỉ khi biến là null?',
  130: 'Nếu dùng biến `late` trước khi khởi tạo thì sao?',
  131: 'Từ khóa nào dùng cho khởi tạo lười (lazy) trong Dart?',
  132: '`late` thường dùng với loại biến nào?',
  133: '`dynamic` trong Dart có nghĩa là gì?',
  134: 'Phần nào sau đây là hợp lệ?',
  135: 'Từ khóa nào cho phép cả int và double?',
  136: 'Làm sao chuyển chuỗi sang int trong Dart?',
  137: 'Làm sao kiểm tra kiểu của một biến?',
  138: 'Cách nào khai báo biến int nullable?',
  139: 'Kiểu dữ liệu của `true` trong Dart là gì?',
  140: 'Khai báo nào sau đây hợp lệ?',
  141: 'Toán tử nào dùng cho phép cộng trong Dart?',
  142: 'Toán tử nào là toán tử so sánh bằng trong Dart?',
  143: 'Toán tử nào dùng để kết hợp hai điều kiện?',
  144: 'Toán tử nào có thể nối chuỗi?',
  145: 'Thư viện (library) trong Dart là gì?',
  146: 'Từ khóa nào dùng để nạp thư viện Dart khác?',
  147: 'Cú pháp đúng để import thư viện built-in?',
  148: 'Phần nào là thư viện cốt lõi của Dart?',
  149: 'Thư viện nào được tự động import vào mọi chương trình Dart?',
  150: 'Làm sao import thư viện kèm alias?',
  151: 'Cú pháp nào chỉ import một phần của thư viện?',
  152: 'Từ khóa nào ẩn một phần thư viện khi import?',
  153: 'Mục đích của `part` và `part of` trong Dart?',
  154: 'Từ khóa nào dùng để ra quyết định trong Dart?',
  155: 'Cú pháp đúng cho câu lệnh `if` trong Dart?',
  156: 'Khối `else` trong Dart chạy khi nào?',
  157: 'Câu lệnh nào dùng để lặp khối mã số lần cố định?',
  158: '`break` trong vòng lặp Dart làm gì?',
  159: '`continue` làm gì?',
  160: 'Vòng lặp nào kiểm tra điều kiện sau khi chạy thân vòng lặp?',
  161: 'Từ khóa nào dùng cho nhiều nhánh thay cho nhiều if-else?',
  162: 'Sau mỗi `case` trong `switch` của Dart cần gì?',
  163: 'Class trong Dart là gì?',
  164: 'Object trong Dart là gì?',
  165: 'Từ khóa nào dùng để định nghĩa class?',
  166: 'Làm sao tạo object trong Dart?',
  167: 'Mục đích của constructor trong class?',
  168: 'Ký hiệu nào dùng để truy cập thuộc tính hoặc method của object?',
  169: 'Mô tả nào đúng nhất về biến instance?',
  170: 'Nếu không định nghĩa constructor trong class Dart thì sao?',
  171: '________ là biểu diễn thời gian thực của một thực thể.',
};
