/** Vietnamese question stems for PRM393 indices that are English-only (part 1: 0–68). */
export const qviA = {
  0: 'Mục đích chính của các câu lệnh điều khiển luồng trong Dart là gì?',
  1: 'Phương thức Provider nào lắng nghe thay đổi và rebuild UI?',
  2: '`context.read()` trong Provider làm gì?',
  3: 'Lợi ích của named routes là gì?',
  4: 'Vai trò chính của Navigator trong Flutter?',
  5: 'Lợi ích của theme tập trung?',
  6: 'UI Flutter được xây dựng bên trong như thế nào?',
  7: 'Flutter framework đóng vai trò gì trong phát triển ứng dụng?',
  8: '`Navigator.pop()` làm gì?',
  9: 'Nếu vi phạm ràng buộc layout trong Flutter thì sao?',
  10: 'Package Flutter nào thường dùng cho lưu key–value đơn giản?',
  11: 'Mục đích chính của widget `Container`?',
  12: 'Mục đích chính của kiến trúc ứng dụng?',
  13: 'Khác biệt chính giữa StatelessWidget và StatefulWidget?',
  14: 'Thuộc tính `version` trong `openDatabase()` dùng để?',
  15: 'Mục đích chính của ngôn ngữ Dart trong Flutter?',
  16: 'Một class Dart chủ yếu biểu diễn điều gì?',
  17: 'Ưu điểm chính khi dùng Provider?',
  18: 'Vì sao cần hiểu vòng đời widget?',
  19: 'Mục đích của callback `onSaved`?',
  20: 'Lợi ích chính của kiến trúc dựa trên widget?',
  21: 'Vai trò chính của widget trong Flutter?',
  22: 'API timeout dùng để?',
  23: 'Cấu trúc điều khiển nào dùng để lặp lại một khối mã trong Dart?',
  24: 'Route trong Flutter là gì?',
  25: 'Lợi ích chính khi dùng Map trong Dart?',
  26: 'Phương thức nào dùng để cập nhật UI khi state đổi?',
  27: 'Nếu local storage thất bại thì sao?',
  28: '`crossAxisAlignment` điều khiển gì?',
  29: 'Khi nào nên ưu tiên Provider hơn setState()?',
  30: 'Dart trong hệ sinh thái Flutter chủ yếu được thiết kế để?',
  31: 'Widget nào thường làm root của app Flutter?',
  32: 'State lifting giúp giải quyết vấn đề gì?',
  33: '`build()` của một widget trả về gì?',
  34: 'Mục đích `focusNode` trong TextField?',
  35: 'Mục đích package `path_provider`?',
  36: 'Câu nào mô tả hệ thống layout của Flutter đúng nhất?',
  37: 'Dùng local storage trong app chủ yếu để?',
  38: 'HTTP method nào thường dùng để lấy dữ liệu?',
  39: 'Session expiration là gì?',
  40: 'Trách nhiệm chính của `setState()`?',
  41: 'Mục đích chính của `ThemeData` trong Flutter?',
  42: 'Package nào cung cấp hỗ trợ SQL trong Flutter?',
  43: 'Vai trò của widget `Expanded`?',
  44: 'Widget nào cho phép các con chồng lên nhau?',
  45: 'Thuộc tính `decoration` của TextField cho phép gì?',
  46: 'Nếu biến non-nullable không được khởi tạo trong Dart thì sao?',
  47: 'Lợi ích chính của InheritedWidget?',
  48: 'Vai trò của widget `Consumer` trong Provider?',
  49: 'Ưu điểm chính của Navigator 2.0?',
  50: 'Flutter là gì?',
  51: 'Ai phát triển Flutter?',
  52: 'Flutter cho phép developer dùng bao nhiêu codebase?',
  53: 'Flutter dùng mô hình UI nào?',
  57: 'Engine Flutter chủ yếu được viết bằng ngôn ngữ nào?',
  61: 'Flutter hỗ trợ những nền tảng nào?',
  62: '`flutter doctor` dùng để làm gì?',
  63: 'Ngôn ngữ nào dùng để viết app Flutter?',
  64: 'Flutter được mô tả đúng nhất là gì?',
  65: 'Flutter render UI bằng gì?',
  68: 'Flutter theo phong cách lập trình nào?',
};
